language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email: jllang@cs.helsinki.fi

install: mvn install -Dmaven.compiler.target=1.7 -Dmaven.compiler.source=1.7 -DskipTests=true -B
script: "./run_tests.sh"
