/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tiralabra_maven.gui;

import com.mycompany.tiralabra_maven.Piirtologiikka;
import com.mycompany.tiralabra_maven.algoritmi.Simulaatio;

/**
 *
 * @author mikko
 */
public class NewJFrame extends javax.swing.JFrame {

    private Simulaatio simulaatio;
    private Piirtologiikka piirtologiikka;
    private int sivunPituus;

    private boolean simulaatioKaynnissa;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame(Simulaatio simulaatio, Piirtologiikka piirtologiikka, int sivunPituus) {
        this.simulaatio = simulaatio;
        this.piirtologiikka = piirtologiikka;
        this.sivunPituus = sivunPituus;
        initComponents();
    }

    public Piirtoalusta getPiirtoalusta() {
        return this.piirtoalusta;
    }
    
    private void poistaValinnat() {
        lattiaButton.setSelected(false);
        seinaButton.setSelected(false);
        aloituspisteButton.setSelected(false);
        maaliButton.setSelected(false);
    }
    
    private void asetaNappienTila(boolean enabled) {
        lattiaButton.setEnabled(enabled);
        seinaButton.setEnabled(enabled);
        aloituspisteButton.setEnabled(enabled);
        maaliButton.setEnabled(enabled);
    }

    private void paivitaKomponentit() {
        if (simulaatioButton.isSelected()) {
            simulaatioButton.setText("Lopeta simulaatio");
            asetaNappienTila(false);
        } else {
            simulaatioButton.setText("Aloita simulaatio");
            asetaNappienTila(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piirtoalusta = new Piirtoalusta(piirtologiikka, sivunPituus);
        HiirenKuuntelija hiirenkuuntelija = new HiirenKuuntelija(sivunPituus, piirtologiikka);
        piirtoalusta.addMouseListener(hiirenkuuntelija);
        piirtoalusta.addMouseMotionListener(hiirenkuuntelija);
        jToolBar1 = new javax.swing.JToolBar();
        simulaatioButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lattiaButton = new javax.swing.JToggleButton();
        seinaButton = new javax.swing.JToggleButton();
        aloituspisteButton = new javax.swing.JToggleButton();
        maaliButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout piirtoalustaLayout = new javax.swing.GroupLayout(piirtoalusta);
        piirtoalusta.setLayout(piirtoalustaLayout);
        piirtoalustaLayout.setHorizontalGroup(
            piirtoalustaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        piirtoalustaLayout.setVerticalGroup(
            piirtoalustaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        simulaatioButton.setText("Aloita simulaatio");
        simulaatioButton.setFocusable(false);
        simulaatioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        simulaatioButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        simulaatioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulaatioButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(simulaatioButton);

        jSeparator1.setOrientation(javax.swing.SwingConstants.HORIZONTAL);
        jToolBar1.add(jSeparator1);

        lattiaButton.setText("Lattia");
        lattiaButton.setFocusable(false);
        lattiaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lattiaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lattiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lattiaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(lattiaButton);

        seinaButton.setText("Seinä");
        seinaButton.setFocusable(false);
        seinaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seinaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seinaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(seinaButton);

        aloituspisteButton.setText("Aloituspiste");
        aloituspisteButton.setFocusable(false);
        aloituspisteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aloituspisteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aloituspisteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aloituspisteButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(aloituspisteButton);

        maaliButton.setText("Maali");
        maaliButton.setFocusable(false);
        maaliButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maaliButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        maaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maaliButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(maaliButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(piirtoalusta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piirtoalusta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seinaButtonActionPerformed
        poistaValinnat();
        seinaButton.setSelected(true);
    }//GEN-LAST:event_seinaButtonActionPerformed

    private void maaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maaliButtonActionPerformed
        // TODO add your handling code here:
        poistaValinnat();
        maaliButton.setSelected(true);
    }//GEN-LAST:event_maaliButtonActionPerformed

    private void simulaatioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulaatioButtonActionPerformed
        // TODO add your handling code here:
        paivitaKomponentit();

    }//GEN-LAST:event_simulaatioButtonActionPerformed

    private void lattiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lattiaButtonActionPerformed
        // TODO add your handling code here:
        poistaValinnat();
        lattiaButton.setSelected(true);
    }//GEN-LAST:event_lattiaButtonActionPerformed

    private void aloituspisteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aloituspisteButtonActionPerformed
        // TODO add your handling code here:
        poistaValinnat();
        aloituspisteButton.setSelected(true);
    }//GEN-LAST:event_aloituspisteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aloituspisteButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton lattiaButton;
    private javax.swing.JToggleButton maaliButton;
    private com.mycompany.tiralabra_maven.gui.Piirtoalusta piirtoalusta;
    private javax.swing.JToggleButton seinaButton;
    private javax.swing.JToggleButton simulaatioButton;
    // End of variables declaration//GEN-END:variables
}
