strassen <- read.csv("strassen.csv")
strassen <- as.matrix(strassen)
naivi <- read.csv("naivi.csv")
naivi <- as.matrix(naivi)
molemmat <- merge(strassen,naivi)
legtxt<-c("Strassen","Naiivi")
pdf("kertolasku.pdf")
plot(strassen,bty="n",xlab="Syötteen koko", ylab="Käytetty aika", type="o",pch=15, col="red")
lines(naivi, type="o", pch=18, col="green")
legend(200,50000,legtxt,bty="n",pch=c(15,18),col=c("red","green"))
dev.off()
