#CppUnit_INCLUDE_DIR
#CppUnit_LIBRARY
#CppUnit_FOUND

find_path(CppUnit_INCLUDE_DIR cppunit/Test.h)
find_library(CppUnit_LIBRARY cppunit)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CppUnit REQUIRED_VARS CppUnit_INCLUDE_DIR CppUnit_LIBRARY)

mark_as_advanced(CppUnit_INCLUDE_DIR CppUnit_LIBRARY)
